services:
  goinspectorgadget:
    image: goinspectorgadget
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
    # Override the default command to keep the container running
    entrypoint: [/bin/sh, -c]
    command: [while true; do sleep 30; done]
    healthcheck:
      test: [CMD, /app/app, help]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s 